apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mar13 
  janus-idp.io/tekton: mar13
  backstage.io/kubernetes-id: mar13
  backstage.io/kubernetes-namespace: mar13 
  app.kubernetes.io/part-of: mar13
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  