apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mar13
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar13 
  name: mar13
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mar13 
